### ISSUE TITLE
How and where should I modify the code when I am reducing the class

### ISSUE THREAD

**Issue by xhangHU** [xieenze/Trans2Seg#14]
When I try to reduce the categories to two while testing, I get the following error：

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorMath.cu line=26 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "tools/train.py", line 330, in <module>
    trainer.train()
  File "tools/train.py", line 170, in train
    losses.backward()
  File "/opt/conda/envs/trans_seg/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/envs/trans_seg/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorMath.cu:26
Traceback (most recent call last):
  File "/opt/conda/envs/trans_seg/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/trans_seg/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/trans_seg/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/envs/trans_seg/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)

How to modify the network parameters to run？
thank you！

**Comment by Liuliuliuliu16** [comment]
Have you solved this problem? I wonder if you could communicate with me
