### ISSUE TITLE
Cannot  follow the train demo

### ISSUE THREAD

**Issue by JinraeKim** [xieenze/Trans2Seg#16]
When I followed the train demo, there were some path errors like

```
(trans2seg) jinrae@costar-Oryx-Pro:~/workspace/Trans2Seg$ bash tools/dist_train.sh configs/trans10kv2/trans2seg/trans2seg_medium.yaml 1
+ CONFIG=configs/trans10kv2/trans2seg/trans2seg_medium.yaml
+ GPUS=8
++ dirname tools/dist_train.sh
+ python -m torch.distributed.launch --nproc_per_node=8 tools/train.py --config-file configs/trans10kv2/trans2seg/trans2seg_medium.yaml 1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
Traceback (most recent call last):
  File "/home/jinrae/miniconda3/envs/trans2seg/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jinrae/miniconda3/envs/trans2seg/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jinrae/miniconda3/envs/trans2seg/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/jinrae/miniconda3/envs/trans2seg/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jinrae/miniconda3/envs/trans2seg/bin/python', '-u', 'tools/train.py', '--local_rank=7', '--config-file', 'configs/trans10kv2/trans2seg/trans2seg_medium.yaml', '1']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'
(trans2seg) jinrae@costar-Oryx-Pro:~/workspace/Trans2Seg$ Traceback (most recent call last):
  File "tools/train.py", line 20, in <module>
    from segmentron.solver.loss import get_segmentation_loss
  File "/home/jinrae/workspace/Trans2Seg/segmentron/solver/loss.py", line 9, in <module>
    from ..models.pointrend import point_sample
ModuleNotFoundError: No module named 'segmentron.models.pointrend'

```

**Comment by JinraeKim** [comment]
Dup of #12
