### ISSUE TITLE
ValueError: Command line options config format error! Please check it:

### ISSUE THREAD

**Issue by akbarxie** [xieenze/Trans2Seg#18]
by input this command:
'''
bash tools/dist_train.sh configs/trans10kv2/trans2seg/trans2seg_medium.yaml 2
'''
but I get error for :
'''
Traceback (most recent call last):
  File "tools/train.py", line 296, in <module>
    cfg.update_from_list(args.opts)
  File "/home/lthpc/Algo/xjw/Trans2Seg/segmentron/config/config.py", line 107, in update_from_list
    raise ValueError(
ValueError: Command line options config format error! Please check it: ['2']''', and I try to check the src code:

'''
    def update_from_list(self, config_list):
        if len(config_list) % 2 != 0:
            raise ValueError(
                "Command line options config format error! Please check it: {}".
                format(config_list))
        for key, value in zip(config_list[0::2], config_list[1::2]):
            try:
                self.__setattr__(key, value, create_if_not_exist=False)
            except KeyError:
                raise KeyError('Non-existent config key: {}'.format(key))'''
I don't konw how to fix it?

**Comment by akbarxie** [comment]
after look into the change log of github,I found the ansewer:
before there was the train code:
'''
CUDA_VISIBLE_DEVICES=0 python -u tools/train.py --config-file configs/cityscapes_deeplabv3_plus.yaml
'''
after the author change to:
'''
bash tools/dist_train.sh configs/trans10kv2/trans2seg/trans2seg_medium.yaml 8
'''
and if we use the first training code ,it works well
